- name: Install yum packages and reboot
  hosts: localhost
  connection: local
  tasks:
    - name: Install yum packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - bzip2
        - genisoimage
        - epel-release
        - yum-utils
        - createrepo
        - gcc
        - kernel
        - kernel-devel
        - kernel-headers
    - name: Start reboot
      shell: shutdown -r